import {Inter} from 'next/font/google'
import './globals.css'
import React from "react";
import NavbarPartial from "@/components/partials/navbar.partial";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const inter = Inter({subsets: ['latin']});

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return <html lang="en" className={inter.className}>
    <body className="m-10 flex">
    <NavbarPartial/>
    {children}
    </body>
    </html>
}
